#!/bin/sh
# Author: Apurva Jatakia(ajatakia at gmial dot com)
# This is a post installation script which adds the Penn Totalrecall repository to apt sources.
DEBCONFIG="deb http://memory.psych.upenn.edu/files/software/TotalRecall/deb/ penntotalrecall main"
DEB_SRCCONFIG="deb-src http://memory.psych.upenn.edu/files/software/TotalRecall/deb/ penntotalrecall main"
APT_CONFIG="`which apt-config 2> /dev/null`"
# Parse apt configuration and return requested variable value.
apt_config_val() {
  APTVAR="$1"
  if [ -x "$APT_CONFIG" ]; then
    "$APT_CONFIG" dump | sed -e "/^$APTVAR /"'!d' -e "s/^$APTVAR \"\(.*\)\".*/\1/"
  fi
}

# Set variables for the locations of the apt sources lists.
find_apt_sources() {
  APTDIR=$(apt_config_val Dir)
  APTETC=$(apt_config_val 'Dir::Etc')
  APT_SOURCES="$APTDIR$APTETC$(apt_config_val 'Dir::Etc::sourcelist')"
}

find_apt_sources
# Nothing to do if it's already there.
    SOURCELIST=$(grep -H "$DEBCONFIG" "$APT_SOURCES" \
      2>/dev/null | cut -d ':' -f 1)
    if [ ! -n "$SOURCELIST" ]; then
      	printf "$DEBCONFIG\n" >> "$APT_SOURCES"
	printf "$DEB_SRCCONFIG\n" >> "$APT_SOURCES"
    fi

